---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - cluster-issuers.yaml

# Note: cert-manager CRDs and controller should be installed via Helm
# This kustomization only includes the ClusterIssuers configuration
# 
# Installation:
#   helm repo add jetstack https://charts.jetstack.io
#   helm repo update
#   helm install cert-manager jetstack/cert-manager \
#     --namespace cert-manager \
#     --create-namespace \
#     --version v1.13.3 \
#     --set installCRDs=true \
#     --set prometheus.enabled=true
