apiVersion: v1
kind: Service
metadata:
  name: vector
  namespace: apisix
spec:
  type: ExternalName
  externalName: vector.vector.svc.cluster.local
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 8080
