apiVersion: v1
kind: Secret
metadata:
  name: clickhouse-users
  namespace: clickhouse
type: Opaque
stringData:
  # Users and passwords
  # Format: username: password
  admin-password: "changeme_admin123"
  writer-password: "changeme_writer123"
  reader-password: "changeme_reader123"
