---
# Kustomization for base resources
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: turia-trails

resources:
  - namespace.yaml
  - rbac/roles.yaml
  - storage-classes/storage-classes.yaml
  - network-policies/policies.yaml

commonLabels:
  app.kubernetes.io/part-of: turia-trails
  app.kubernetes.io/managed-by: kustomize
