---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - metrics-server.yaml

# Note: For full observability stack, install kube-prometheus-stack via Helm:
#
#   helm repo add prometheus-community https://prometheus-community.github.io/helm-charts
#   helm repo update
#   helm install prometheus prometheus-community/kube-prometheus-stack \
#     --namespace kube-monitoring \
#     --create-namespace \
#     --values prometheus-values.yaml
