apiVersion: v1
kind: Secret
metadata:
  name: postgres-creds
  namespace: postgresql
type: Opaque
stringData:
  postgres-password: "changeme_postgres123"
  pgbouncer-password: "changeme_pgbouncer123"
  replication-password: "changeme_repl123"
