global:
  postgresql:
    auth:
      existingSecret: "postgres-creds"
      secretKeys:
        adminPasswordKey: "postgres-password"
        replicationPasswordKey: "replication-password"

architecture: standalone

primary:
  resources:
    requests:
      cpu: 250m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 512Mi
  persistence:
    enabled: true
    storageClass: "standard-ssd"
    size: 8Gi
  initdb:
    user: postgres
    password: changeme_postgres123
    scriptsConfigMap: "postgres-init-scripts"

auth:
  enablePostgresUser: true
  database: "turia_trails"


