apiVersion: v1
data:
  config.yaml: |
    # from .Values.config
    kafka:
      brokers:
      - redpanda-0.redpanda.redpanda.svc.cluster.local.:9093
      - redpanda-1.redpanda.redpanda.svc.cluster.local.:9093
      - redpanda-2.redpanda.redpanda.svc.cluster.local.:9093
      sasl:
        enabled: true
        mechanism: SCRAM-SHA-256
        username: kubernetes-controller
      tls:
        caFilepath: /etc/tls/certs/secrets/redpanda-default-cert/ca.crt
        enabled: true
        insecureSkipVerify: true
    redpanda:
      adminApi:
        enabled: true
        tls:
          caFilepath: /etc/tls/certs/secrets/redpanda-default-cert/ca.crt
          enabled: true
        urls:
        - https://redpanda.redpanda.svc.cluster.local.:9644
    schemaRegistry:
      authentication:
        basic:
          username: kubernetes-controller
      enabled: true
      tls:
        caFilepath: /etc/tls/certs/secrets/redpanda-default-cert/ca.crt
        enabled: true
      urls:
      - https://redpanda-0.redpanda.redpanda.svc.cluster.local.:8081
      - https://redpanda-1.redpanda.redpanda.svc.cluster.local.:8081
      - https://redpanda-2.redpanda.redpanda.svc.cluster.local.:8081
kind: ConfigMap
metadata:
  annotations:
    meta.helm.sh/release-name: redpanda
    meta.helm.sh/release-namespace: redpanda
  creationTimestamp: "2025-12-06T13:39:38Z"
  labels:
    app.kubernetes.io/instance: redpanda
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: console
    app.kubernetes.io/version: v3.3.2
    helm.sh/chart: console-3.3.0
  name: redpanda-console
  namespace: redpanda
  resourceVersion: "924469"
  uid: dd3a468f-436b-45c9-8d8f-ca0bc34d9617
